### ISSUE TITLE
Phrase SDK crash webview on forms opening AlertDialog

### ISSUE THREAD

**Issue by debase** [phrase/phrase-android#60]
##  Context
We are using phrase SDK 3.5.0 in our project opening in app webviews containing \<fieldset\> html property which basically tries to open an alert dialog.

## Observed behavior
When opening a in app webviews url containing \<fieldset\> property when clicking on it to select, the app crash with stack trace:

```
Process: com.example.phraseotacrashwebviews, PID: 32444
              android.content.res.Resources$NotFoundException: Resource ID #0x0
               at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:226)
               at android.content.res.Resources.loadXmlResourceParser(Resources.java:2504)
               at android.content.res.Resources.getLayout(Resources.java:1261)
               at androidx.appcompat.widget.ResourcesWrapper.getLayout(ResourcesWrapper.java:204)
               at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
               at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:425)
               at android.widget.ArrayAdapter.getView(ArrayAdapter.java:416)
               at WV.rj0.getView(chromium-TrichromeWebViewGoogle6432.aab-stable-584516333:11)
               at android.widget.AbsListView.obtainView(AbsListView.java:2421)
               at android.widget.ListView.measureHeightOfChildren(ListView.java:1417)
               at android.widget.ListView.onMeasure(ListView.java:1323)
               at android.view.View.measure(View.java:26362)
               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
               at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
               at android.view.View.measure(View.java:26362)
               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
               at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
               at android.view.View.measure(View.java:26362)
               at com.android.internal.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:146)
               at com.android.internal.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:71)
               at android.view.View.measure(View.java:26362)
               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
               at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
               at android.view.View.measure(View.java:26362)
               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
               at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
               at android.view.View.measure(View.java:26362)
               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
               at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
               at com.android.internal.policy.DecorView.onMeasure(DecorView.java:758)
               at android.view.View.measure(View.java:26362)
               at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3916)
               at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2609)
               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2902)
               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2354)
               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9078)
               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1346)
               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1354)
               at android.view.Choreographer.doCallbacks(Choreographer.java:1005)
               at android.view.Choreographer.doFrame(Choreographer.java:936)
               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
               at android.os.Handler.handleCallback(Handler.java:942)
               at android.os.Handler.dispatchMessage(Handler.java:99)
               at android.os.Looper.loopOnce(Looper.java:227)
               at android.os.Looper.loop(Looper.java:327)
               at android.app.ActivityThread.main(ActivityThread.java:7995)
               at java.lang.reflect.Method.invoke(Native Method)
               at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```

## Expected behavior
App should not crash on selection and should open the alert dialog

## Step to reproduce
Sample project [here](https://we.tl/t-KbHwi4JhQk) which just open url "https://eu.claims.axa.travel/claim_form/form" in a webview
Just clicking on "country of residence" form field make the app crash.
Commenting `override fun getDelegate(): AppCompatDelegate`solve the issue.

**Comment by theSoenke** [comment]
@debase thank you for even preparing a sample project. That's really helpful and I've prepared a task to resolve this. I'll keep you posted here

**Comment by theSoenke** [comment]
Hi @debase, this should be resolved in version https://github.com/phrase/phrase-android/releases/tag/3.7.1. Could you try it with the latest release?

**Comment by Valentin-Buculei** [comment]
For me the issue still happens in 3.7.3

> android.content.res.Resources$NotFoundException: Resource ID #0x0
                                 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:265)
                                 	at android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:96)
                                 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2607)
                                 	at android.content.res.Resources.getLayout(Resources.java:1314)
                                 	at androidx.appcompat.widget.ResourcesWrapper.getLayout(ResourcesWrapper.java:204)
                                 	at android.view.LayoutInflater.inflate(LayoutInflater.java:537)
                                 	at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:425)
                                 	at android.widget.ArrayAdapter.getView(ArrayAdapter.java:416)
                                 	at WV.DM.getView(chromium-TrichromeWebViewGoogle6432.aab-stable-604506633:11)
                                 	at android.widget.AbsListView.obtainView(AbsListView.java:2424)
                                 	at android.widget.ListView.measureHeightOfChildren(ListView.java:1417)
                                 	at android.widget.ListView.onMeasure(ListView.java:1323)
                                 	at android.view.View.measure(View.java:26640)
                                 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7060)
                                 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                 	at android.view.View.measure(View.java:26640)
                                 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7060)
                                 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                 	at android.view.View.measure(View.java:26640)
                                 	at com.android.internal.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:146)
                                 	at com.android.internal.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:71)
                                 	at android.view.View.measure(View.java:26640)
                                 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7060)
                                 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                 	at android.view.View.measure(View.java:26640)
                                 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7060)
                                 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                 	at android.view.View.measure(View.java:26640)
                                 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7060)
                                 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:835)
                                 	at android.view.View.measure(View.java:26640)
                                 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4145)
                                 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2810)
                                 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3116)
                                 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2546)
                                 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9498)
                                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1459)
                                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1467)
                                 	at android.view.Choreographer.doCallbacks(Choreographer.java:1089)
                                 	at android.view.Choreographer.doFrame(Choreographer.java:1003)
                                 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1435)
                                 	at android.os.Handler.handleCallback(Handler.java:942)
                                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                                 	at android.os.Looper.loopOnce(Looper.java:211)
                                 	at android.os.Looper.loop(Looper.java:300)
                                 	at android.app.ActivityThread.main(ActivityThread.java:8395)
                                 	at java.lang.reflect.Method.invoke(Native Method)
                                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
                                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by valeriiia** [comment]
Hi.
I also experience this issue in 3.7.3.

**Comment by theSoenke** [comment]
Hi @Valentin-Buculei and @valeriiia, thanks for the report. Does this issue occur for you when opening the alert dialog as well or a different action inside a webview?

**Comment by valeriiia** [comment]
Hi.
For me it occurs when one tries to pick a date and time on the webview.
When the date/time dialog appears the app crashes. Once we've disabled the
Phrase this crash disappear

Cheers,
Valeriia

**Comment by Valentin-Buculei** [comment]
> Hi @Valentin-Buculei and @valeriiia, thanks for the report. Does this issue occur for you when opening the alert dialog as well or a different action inside a webview?

yes, when it opens a dialog (after clicking on a <select> element)

**Comment by valeriiia** [comment]
Hello. Are there any updates on this issue or any workarounds? Thanks

**Comment by theSoenke** [comment]
Hey @valeriiia, unfortunately I don't have an update yet. There are 1-2 things we'll have to resolve before in the SDK and then this will be next priority to resolve.

**Comment by Valentin-Buculei** [comment]
> Hello. Are there any updates on this issue or any workarounds? Thanks

A workaround would be to open the dialog from a new, translucent activity that does not call `Phrase.getDelegate()`

**Comment by bartlomiej-sory-home24** [comment]
We are also affected by the same issue, crashes started spiking recently without any reason.

The only fix seems to be to not call `Phrase.getDelegate()` on the activity. It is not reproducible on every device

When a fix can be expected ?

**Comment by hahmed-dev** [comment]
The latest release [3.10.0](https://github.com/phrase/phrase-android/releases/tag/3.10.0), includes fixes for crashes experienced in Webview when opening alert dialogs.

**Comment by valeriiia** [comment]
The 3.10.1 release solved the problem indeed. However, I see the following information about the next 3.10.2 release 
"
Bugfixes:
Reverts changes introduced in release 3.10.1 which can potentially lead to app crashing.
"
Does it mean that fix for crashes experienced in Webview are back again? 
Could you please clarify it?

**Comment by hahmed-dev** [comment]
Hi @valeriiia actually the after `3.10.0` there were still some reports of this issue appearing in Xiaomi devices. A potential fix was made in `3.10.1` which caused some regression. Hence, we have just reverted the fix made in `3.10.1`, fixes that were shipped in `3.10.0` should still work.

**Comment by WaqarAhmadGit** [comment]
@hahmed-dev We are also encountering a similar issue on Xiaomi devices despite being on the latest version. Could you please provide an update on when we can expect a fix for Xiaomi devices?

**Comment by hahmed-dev** [comment]
Hi @WaqarAhmadGit in your case, is the application crashing on Xiaomi devices? Specifically when using webview? Could you provide some details please?

**Comment by WaqarAhmadGit** [comment]
@hahmed-dev thank you so much for your response, yes app is crashing specifically on Xiomi devices as we have more than 12 apps and we are using Phrase for translations.
Do you need a crash report?

**Comment by hahmed-dev** [comment]
Hi @WaqarAhmadGit , if you can attach that and the version of SDK you are using, that would be great.

**Comment by hahmed-dev** [comment]
Thanks @WaqarAhmadGit. We plan to address the issues being encountered in Xiaomi devices in one of the upcoming sprints. Right now we are working on addressing some performance issues introduced in release 3.10.x. I'll keep you posted on the timeline of this.

**Comment by ricardobranco** [comment]
After updating to 3.10.2, the issue still persists. Currently, all affected devices are Xiaomi models. There is any way to disable Phrase only for webviews?

**Comment by WaqarAhmadGit** [comment]
Hey @hahmed-dev, do you have any updates related to this issue? 🙏

**Comment by theSoenke** [comment]
Unfortunately there's no update to announce yet. Webviews are deeply coupled to other Android resources that those cannot be easily separated. Right now the focus is on improving test coverage to uncover cases where Android behaves differently depending on the version or device. As soon as there is an update it will be posted on this issue
